version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: abi
      POSTGRES_PASSWORD: tulangayam
      POSTGRES_DB: store
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db